//
//  FavouritesPresenter.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouritesPresenter: FavouritesPresenterProtocol {

    weak private var view: FavouritesViewProtocol?
    var interactor: FavouritesInteractorProtocol?
    private let router: FavouritesWireframeProtocol

    init(interface: FavouritesViewProtocol, interactor: FavouritesInteractorProtocol?, router: FavouritesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
