//
//  SearchViewControllerPresenter.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewControllerPresenter: SearchViewControllerPresenterProtocol {

    weak private var view: SearchViewControllerViewProtocol?
    var interactor: SearchViewControllerInteractorProtocol?
    private let router: SearchViewControllerWireframeProtocol

    init(interface: SearchViewControllerViewProtocol, interactor: SearchViewControllerInteractorProtocol?, router: SearchViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
