//
//  SearchViewControllerRouter.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewControllerRouter: SearchViewControllerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: SearchViewControllerViewController) {
        
        let interactor = SearchViewControllerInteractor()
        let router = SearchViewControllerRouter()
        let presenter = SearchViewControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

    }
}
