//
//  SearchViewControllerProtocols.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchViewControllerWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchViewControllerPresenterProtocol: class {

}

//MARK: Interactor -
protocol SearchViewControllerInteractorProtocol: class {

  var presenter: SearchViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchViewControllerViewProtocol: class {

  var presenter: SearchViewControllerPresenterProtocol?  { get set }
}
