//
//  SearchViewControllerInteractor.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewControllerInteractor: SearchViewControllerInteractorProtocol {

    weak var presenter: SearchViewControllerPresenterProtocol?
}
