//
//  VideoViewController.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoViewController: UIViewController, VideoViewProtocol {

	var presenter: VideoPresenterProtocol?
    
    @IBOutlet weak var videosTableView: UITableView!
    
    var dateArray = [VideoModel]()

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.title = "VIDEO"
        
        if !(dateArray.isEmpty) {
            setImageWhenNoData(image: UIImage(), widthImage: 150, heightImage: 150, textDescroption: "", hidden: true)
        } else {
            setImageWhenNoData(image: UIImage(), widthImage: 150, heightImage: 150, textDescroption: "No Results", hidden: false)
        }
    }

}
