//
//  VideoRouter.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoRouter: VideoWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: VideoViewController) {
        let interactor = VideoInteractor()
        let router = VideoRouter()
        let presenter = VideoPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

    }
}
