//
//  VideoInteractor.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoInteractor: VideoInteractorProtocol {

    weak var presenter: VideoPresenterProtocol?
}
