//
//  VideoProtocols.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VideoWireframeProtocol: class {

}
//MARK: Presenter -
protocol VideoPresenterProtocol: class {

}

//MARK: Interactor -
protocol VideoInteractorProtocol: class {

  var presenter: VideoPresenterProtocol?  { get set }
}

//MARK: View -
protocol VideoViewProtocol: class {

  var presenter: VideoPresenterProtocol?  { get set }
}
