//
//  StoriesInteractor.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift

class StoriesInteractor: StoriesInteractorProtocol {

    weak var presenter: StoriesPresenterProtocol?
    
    var api: ApiManager
    
    init() {
        api = ApiManager.api
    }
    
    func getPopularVideos(page: Int) -> Observable<[VideoModel]> {
        return api.getPopularVideos(page: page)
            .map {
                let data = $0.results
                return data
        }
    }
    
    func getTopRatedVideos(page: Int) -> Observable<[VideoModel]> {
        return api.getTopRatedVideos(page: page)
            .map {
                let data = $0.results
                return data
        }
    }
}
