//
//  StoriesRouter.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class StoriesRouter: StoriesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: StoriesViewController) {

        let interactor = StoriesInteractor()
        let router = StoriesRouter()
        let presenter = StoriesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

    }
}
