//
//  StoriesProtocols.swift
//  lampa
//
//  Created Oleg Pogosian on 23.05.2020.
//  Copyright © 2020 Oleg Pogosian. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol StoriesWireframeProtocol: class {

}
//MARK: Presenter -
protocol StoriesPresenterProtocol: class {
    
    func getPopularVideos(page: Int)
    func getTopRatedVideos(page: Int)

}

//MARK: Interactor -
protocol StoriesInteractorProtocol: class {

  var presenter: StoriesPresenterProtocol?  { get set }
    func getPopularVideos(page: Int) -> Observable<[VideoModel]>
    func getTopRatedVideos(page: Int) -> Observable<[VideoModel]>
    
}

//MARK: View -
protocol StoriesViewProtocol: class {

  var presenter: StoriesPresenterProtocol?  { get set }
    func getPopularSuccess(data: [VideoModel])
    func getTopRatedSuccess(data: [VideoModel])
    func showProgress()
    func hideProgress()
    
}
